---
title: "Model7"
author: "Venkata babu Aalapati"
date: "11/29/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(utf8)
library(ggplot2)
library(aod)
library(outliers)
library(readxl)
library(Hmisc)
```

```{r}
#loading the data set
df_good_belly <- read_excel("Goodbelly_Project_Data.xlsx")
#removing null values from the data set
na.omit(df_good_belly)

```

Model7:
(Model3+: Demo/Demo Interactions)
Sales = β0 + β1Region + β2Endcap + β3Demo + β4Demo1.3 + β5Demo4.5 
+β6Region∗Endcap+β7Sales_Rep+β8Store+Store*Endcap+β9ARP

```{r}

#Building basic regression model
Model7<-lm(formula = Sales ~ ARP+Region+Endcap+Demo+Demo1.3+Demo4.5
             +Region*Endcap+Sales_Rep+Store+Store*Endcap,
            data = df_good_belly)
#Understanding summary results of the model 
summary(Model7)
# Plotting fitted residuals  model
plot(Model7, which=1, col=c("blue"))

# Plotting residuals and find the variation left by unexplained by the model
df_good_belly$predicted <- predict(Model7)   # Save the predicted values
df_good_belly$residuals <- residuals(Model7) # Save the residual values
ggplot(df_good_belly, aes(x = Region, y = Sales)) +
  geom_smooth(method = "lm", se = FALSE, color = "lightgrey") +    
  geom_segment(aes(xend = Region, yend = predicted), alpha = .2) +      
  geom_point(aes(color = abs(residuals), size = abs(residuals))) +  
  scale_color_continuous(low = "green", high = "red") +             
  guides(color = FALSE, size = FALSE) +                             
  geom_point(aes(y = predicted), shape = 1) +
  theme_bw()

```
```{r}
#Generating CI intervals for coefficients with alpha 0.10
confint(Model7,level = 0.90)
confint.default(Model7)
```

```{r}
#Generating CI intervals for coefficients with alpha 0.10
confint(Model7,level = 0.90)
confint.default(Model7)
coef(Model7)
#Generating CI intervals for odds ratio of coefficients with alpha 0.10
exp(coef(Model7))
exp(cbind(OR = coef(Model7), confint(Model7,level = 0.90)))
```

```{r}
#Further analysis with on residuals with diagnostic plots 
opar <- par(mfrow = c(2,2), oma = c(0, 0, 1.1, 0)) 
plot(Model7, las = 1)
```

Model7a:
(Model3+: Demo/Demo Interactions)
Sales = β0 + β1Region + β2Endcap + β3Demo + β4Demo1.3 + β5Demo4.5 
+β6Sales_Rep∗Endcap+β7Sales_Rep+β8Store+Store*Endcap+β9ARP

```{r}
#Building basic regression model
Model7a<-lm(formula = Sales ~ ARP+Region+Endcap+Demo+Demo1.3+Demo4.5
             +Sales_Rep+Sales_Rep*Endcap+Store+Store*Endcap,
            data = df_good_belly)
#Understanding summary results of the model 
summary(Model7a)
# Plotting fitted residuals  model
plot(Model7a, which=1, col=c("blue"))

# Plotting residuals and find the variation left by unexplained by the model
df_good_belly$predicted <- predict(Model7a)   # Save the predicted values
df_good_belly$residuals <- residuals(Model7a) # Save the residual values
ggplot(df_good_belly, aes(x = Store, y = Sales)) +
  geom_smooth(method = "lm", se = FALSE, color = "lightgrey") +    
  geom_segment(aes(xend = Store, yend = predicted), alpha = .2) +      
  geom_point(aes(color = abs(residuals), size = abs(residuals))) +  
  scale_color_continuous(low = "green", high = "red") +             
  guides(color = FALSE, size = FALSE) +                             
  geom_point(aes(y = predicted), shape = 1) +
  theme_bw()
```

```{r}
#Generating CI intervals for coefficients with alpha 0.10
confint(Model7a,level = 0.90)
confint.default(Model7a)

#Generating CI intervals for odds ratio of coefficients with alpha 0.10
exp(coef(Model7a))
exp(cbind(OR = coef(Model7a),confint(Model7a,level = 0.90)))
```

```{r}
#Further analysis with on residuals with diagnostic plots 
opar <- par(mfrow = c(2,2), oma = c(0, 0, 1.1, 0)) 
plot(Model7a, las = 1)
```

